/*
 * checkers.h
 *
 *  Created on: Jun 11, 2025
 *      Author: mishcat
 */

#ifndef INC_CHECKERS_H_
#define INC_CHECKERS_H_

#define CHECKERS_QUEEN_FLAG (0b10000000)

enum checkersStates {
	CHECKERS_STATE_START,
	CHECKERS_STATE_PLAY,
	CHECKERS_STATE_RESPONSE,
	CHECKERS_STATE_LOSER,
	CHECKERS_STATE_WINNER
};

enum checkersBoardStates {
	CHECKERS_BOARD_ILLEGAL,
	CHECKERS_BOARD_WHITE,
	CHECKERS_BOARD_BLACK,
	CHECKERS_BOARD_EMPTY
};

enum checkersColors {
	CHECKERS_COLOR_EMPTY = FOREGROUND_BLACK,
	CHECKERS_COLOR_WHITE = FOREGROUND_CYAN,
	CHECKERS_COLOR_BLACK = FOREGROUND_RED,
	CHECKERS_COLOR_SELECTED = FOREGROUND_YELLOW,
	CHECKERS_COLOR_CHOICE = FOREGROUND_PURPLE
};

void checkersCheckPossibleMoves(uint8_t x, uint8_t y, uint8_t enemy);

#endif /* INC_CHECKERS_H_ */
